-- 코드를 입력하세요
# SELECT BOOK_ID, SUM(SALES) FROM BOOK_SALES 
#     WHERE SALES_DATE LIKE '2022-01%'
#     GROUP BY BOOK_ID;
    
# SELECT B.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY FROM BOOK A JOIN AUTHOR B
#     ON A.AUTHOR_ID = B.AUTHOR_ID
#     WHERE (A.BOOK_ID, SUM(SALES)) IN (SELECT BOOK_ID, SUM(SALES) FROM BOOK_SALES WHERE SALES_DATE LIKE '2022-01%' GROUP BY BOOK_ID);
    
SELECT A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, SUM(A.PRICE*C.SALES) as TOTAL_SALES
    FROM BOOK A 
    JOIN AUTHOR B ON A.AUTHOR_ID = B.AUTHOR_ID
    JOIN BOOK_SALES C ON A.BOOK_ID = C.BOOK_ID
    WHERE C.SALES_DATE LIKE '2022-01%'
    GROUP BY 1, 3
    ORDER BY 1, 3 DESC;