-- 코드를 입력하세요
with car as(
    SELECT A.*, B.CAR_TYPE, B.DAILY_FEE FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A JOIN CAR_RENTAL_COMPANY_CAR B ON A.CAR_ID = B.CAR_ID
        WHERE B.CAR_TYPE IN ('세단', 'SUV') AND A.CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE ('2022-11-01' BETWEEN START_DATE AND END_DATE) OR ('2022-11-31' BETWEEN START_DATE AND END_DATE)
                                                              )
    GROUP BY A.CAR_ID
)


SELECT A.CAR_ID, A.CAR_TYPE,FLOOR(A.DAILY_FEE * 30 * ((100-discount_rate)/100))FEE FROM car A JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B ON A.CAR_TYPE = B.CAR_TYPE
    WHERE DURATION_TYPE = '30일 이상' AND (FLOOR(A.DAILY_FEE * 30 * ((100-discount_rate)/100)) >= 500000) AND (FLOOR(A.DAILY_FEE * 30 * ((100-discount_rate)/100)) < 2000000)
    ORDER BY FEE DESC,2,1 ;
    
# SELECT * FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
# WHERE car_id =27
# ORDER BY HISTORY_ID