-- 코드를 입력하세요
SELECT A.ANIMAL_ID, A.ANIMAL_TYPE,A.NAME FROM ANIMAL_OUTS A JOIN ANIMAL_INS B USING(ANIMAL_ID)
    WHERE (A.SEX_UPON_OUTCOME LIKE '%Spayed%' OR A.SEX_UPON_OUTCOME LIKE '%Neutered%') AND B.SEX_UPON_INTAKE LIKE '%Intact%'
    ORDER BY 1