-- 코드를 입력하세요
SELECT YEAR(A.SALES_DATE) YEAR, MONTH(A.SALES_DATE) MONTH, B.GENDER GENDER, COUNT(distinct B.USER_ID) USERS FROM ONLINE_SALE A JOIN USER_INFO  B
    ON A.USER_ID = B.USER_ID
    WHERE B.GENDER IS NOT NULL
    GROUP BY 1,2,3
    ORDER BY 1,2,3
    
# SELECT YEAR(SALES_DATE)YEAR, MONTH(SALES_DATE)MONTH, GENDER, COUNT(A.USER_ID)USERS FROM USER_INFO as A ,ONLINE_SALE as B
#     WHERE A.USER_ID = B.USER_ID AND GENDER IS NOT NULL
#     GROUP BY 1,2,3
#     ORDER BY 1,2,3
        
# SELECT YEAR(SALES_DATE)YEAR, MONTH(SALES_DATE)MONTH, GENDER,COUNT( i.USER_ID)USERS
# FROM USER_INFO as i,ONLINE_SALE as o
# WHERE i.USER_ID = o.USER_ID
# AND GENDER is not null
# GROUP BY 1,2,3
# ORDER BY 1,2,3

# SELECT B.GENDER, COUNT(*) FROM ONLINE_SALE A JOIN USER_INFO B
#     ON A.USER_ID = B.USER_ID
#     WHERE A.SALES_DATE LIKE '2022-01%' AND B.GENDER IS NOT NULL
#     GROUP BY B.GENDER
    
# SELECT * FROM USER_INFO