-- 코드를 입력하세요
SELECT A.PRODUCT_ID, B.PRODUCT_NAME, SUM(A.AMOUNT*B.PRICE) TOTAL_SALES FROM FOOD_ORDER A JOIN FOOD_PRODUCT B USING(PRODUCT_ID)
    WHERE A.PRODUCE_DATE LIKE "2022-05%"
    GROUP BY A.PRODUCT_ID
    ORDER BY TOTAL_SALES DESC, PRODUCT_ID;
    
# SELECT * FROM FOOD_ORDER A JOIN FOOD_PRODUCT B USING(PRODUCT_ID)
#     WHERE A.PRODUCE_DATE LIKE "2022-05%"
#     GROUP BY A.PRODUCT_ID