-- 코드를 입력하세요
with ju as (
    SELECT SHIPMENT_ID, FLAVOR, SUM(TOTAL_ORDER)TOTAL_ORDER FROM JULY GROUP BY FLAVOR
), j as (
    SELECT A.SHIPMENT_ID, A.FLAVOR, A.TOTAL_ORDER+B.TOTAL_ORDER S FROM ju A JOIN FIRST_HALF B ON A.FLAVOR = B.FLAVOR
)


SELECT FLAVOR FROM j
    ORDER BY S DESC
    LIMIT 3 ;
