-- 코드를 입력하세요
with ap as(
    SELECT A.APNT_YMD, A.APNT_NO,A.PT_NO,A.MCDP_CD,B.DR_NAME FROM APPOINTMENT A JOIN DOCTOR B ON A.MDDR_ID = B.DR_ID WHERE APNT_YMD LIKE '2022-04-13%' AND APNT_CNCL_YN = 'N' AND A.MCDP_CD = 'CS'
), ap2 as(
    SELECT A.*, B.PT_NAME FROM ap A JOIN PATIENT B ON A.PT_NO = B.PT_NO
)

SELECT APNT_NO, PT_NAME, PT_NO, MCDP_CD, DR_NAME, APNT_YMD FROM ap2
ORDER BY APNT_YMD