-- 코드를 입력하세요
with rm as(
    SELECT B.MEMBER_NAME, B.MEMBER_ID FROM REST_REVIEW A JOIN MEMBER_PROFILE B USING(MEMBER_ID)
    GROUP BY MEMBER_ID
    ORDER BY COUNT(REVIEW_ID) DESC
    LIMIT 1
)


SELECT A.MEMBER_NAME, B.REVIEW_TEXT, DATE_FORMAT(B.REVIEW_DATE, "%Y-%m-%d")REVIEW_DATE FROM rm A JOIN REST_REVIEW B ON A.MEMBER_ID = B.MEMBER_ID
ORDER BY REVIEW_DATE, 2
    
# SELECT * FROM REST_REVIEW 
#     WHERE REST_ID = '00001'