-- 코드를 작성해주세요

with fe as(
    SELECT SUM(CODE) CODE FROM SKILLCODES WHERE CATEGORY = 'Front End'
), abcd as(
    SELECT CASE
        WHEN (SKILL_CODE & (SELECT CODE FROM fe)) AND (SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python')) THEN 'A'
        WHEN SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') THEN 'B'
        WHEN SKILL_CODE & (SELECT CODE FROM fe) THEN 'C'
        END as GRADE, ID, EMAIL
    FROM DEVELOPERS
)


# SELECT CASE
#     WHEN SKILL_CODE & (SELECT * FROM fe) 
#     AND SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') THEN 'A'
#     WHEN SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') THEN 'B'
#     WHEN SKILL_CODE & (SELECT * FROM fe) THEN 'C'
#     END as GRADE, ID, EMAIL
# FROM DEVELOPERS
# WHERE 1 IS NOT NULL
# ORDER BY 1,2


SELECT GRADE, ID, EMAIL FROM abcd
    WHERE GRADE IS NOT NULL
    ORDER BY 1,2;